apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombcrypto
spec:
  selector:
    matchLabels:
      app: bombcrypto
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: bombcrypto
    spec:
      containers:
        - name: bombcrypto
          image: '{{ .Values.werf.image.bombcrypto }}'
          workingDir: /app
          env:
            - name: EKP_PLUGIN_ID
              value: 'bombcrypto'
            - name: EKP_PLUGIN_NAME
              value: 'Bomb Crypto'
            - name: MORALIS_APP_ID
              value: '{{ .Values.moralis.appId }}'
            - name: MORALIS_SERVER_URL
              value: '{{ .Values.moralis.serverUrl }}'
            - name: MONGO_HOST
              value: '{{ .Values.mongodb.host }}'
            - name: REDIS_HOST
              value: 'ekp-bombcrypto-redis-master'
            - name: OPENSEA_API_KEY
              value: '{{ .Values.opensea.apiKey }}'
          ports:
            - containerPort: 3001
              protocol: TCP
